[[release_notes_714]]
=== 7.14 Release notes

[discrete]
[[release_notes_7141]]
=== 7.14.1 Release notes

==== Dependency fix

Updates dependency on `elasticsearch-transport` to be more open. At least 7.11 is required, but this way it can be used with different versions of the `elasticsearch` gem (bigger than or equal to `7.11`) in the same project, without a conflict in `elasticsearch-transport`. When instantiating transport, we now check if version is `< 7.14` so we use the right class.

[discrete]
[[release_notes_7140]]
=== 7.14.0 Release notes

[discrete]
==== General

- Tested with Elastic Enterprise Search API version 7.14.0.

[discrete]
==== App Search

- Adds API Key endpoints: `api_key`, `create_api_key`, `delete_api_key`, `list_api_keys`, `put_api_key`

[discrete]
==== Workplace Search

- Adds synonym set endpoints: `create_batch_synonym_sets`, `delete_synonym_set`, `list_synonym_sets`, `put_synonym_set`, `synonym_set`
- Adds `current_user` endpoint
- Adds `command_sync_jobs` endpoint
- Adds `delete_documents_by_query` endpoint
- Adds `put_content_source_icons` endpoint
