[[release_notes_82]]
=== 8.2 Release notes

[discrete]
[[release_notes_821]]
=== 8.2.1 Release notes

- Adds tracer parameters to enable tracing in elastic-transport. See https://www.elastic.co/guide/en/enterprise-search-clients/ruby/current/overview.html#_logging[logging] for more information.
- Updates Workplace Search OAuth implementation. See https://www.elastic.co/guide/en/enterprise-search-clients/ruby/current/workplace-search-api.html#ws-oauth-authentication[OAuth Authentication] for changes in the OAuth process.

[discrete]
[[release_notes_820]]
=== 8.2.0 Release notes

[discrete]
==== General

- Tested with Elastic Enterprise Search API version 8.2.0.
- Tested with Ruby 2.7, 3.0, 3.1, JRuby 9.3. Older versions of Ruby have reached end of life and been removed from the testing matrices. Minimum required Ruby version is Ruby 2.6 to keep compatibility with JRuby 9.3, but it may be upgraded to 2.7 once JRuby 9.4 comes out.

[discrete]
==== App Search
[discrete]
==== New APIs

* Adds Elasticsearch Search API (In Technical Preview): Utilize the API to passthrough and execute raw Elasticsearch queries against the indices that power Enterprise Search engines.

+
[source,rb]
----------------------------
es_request = { body: { query: { bool: { must: { term: { title: 'test' } } } } } }
client.search_es_search(engine_name, body: { request: es_request })
----------------------------

* Adds Search Explain API: Submit a search and retrieve an Elasticsearch query.
+
[source,rb]
----------------------------
response = client.search_explain(engine_name, body: { query: 'test' })
response.body['query_string']
# => "GET enterprise-search-engine-app-search-explain/_search"
----------------------------
