steps:
  - label: ":elastic-enterprise-search: Enterprise Search :rspec: API Integration Tests :ruby: v{{ matrix.ruby }}"
    agents:
      provider: "gcp"
    env:
      RUBY_VERSION: "{{ matrix.ruby }}"
      STACK_VERSION: 7.17-SNAPSHOT
    matrix:
      setup:
        ruby:
          - "3.2"
          - "3.1"
          - "3.0"
          - "2.7"
    command: ./.buildkite/run-tests.sh
    artifact_paths: "tmp/*"
  - wait: ~
    continue_on_failure: true
  - label: "Log Results"
    command: ./.buildkite/log-results.sh
