steps:
  - label: ":elastic-enterprise-search: :ruby: Enterprise Search Ruby ({{ matrix.ruby }})"
    agents:
      provider: "gcp"
    env:
      RUBY_VERSION: "{{ matrix.ruby }}"
      SERVICE: "{{ matrix.service }}"
      STACK_VERSION: 8.6-SNAPSHOT
    matrix:
      setup:
        ruby:
          - "3.2"
          - "3.1"
          - "3.0"
          - "2.7"
        service:
          - enterprisesearch
          - appsearch
          - workplacesearch
    command: ./.buildkite/run-tests.sh
    artifact_paths: "tmp/*"
  - wait: ~
    continue_on_failure: true
  - label: "Log Results"
    command: ./.buildkite/log-results.sh
