name: Compatibility with Elasticsearch
on: [push, pull_request]

jobs:
  elasticsearch:
    env:
      ES_VERSION: ${{ matrix.es_version }}
    strategy:
      matrix:
        es_version: [ 7.11, 7.12, 7.13, 7.14, 7.15 ]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.0
    - name: Build Gemfile with Elasticsearch gem
      run: |
        ruby -v
        cd ./.github/compatibility/ && bundle
