name: rubocop
on: [push, pull_request]

jobs:
  rubocop:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3
    - name: Run Rubocop
      run: |
        gem install rubocop
        rubocop
