name: main
on: [push, pull_request]

jobs:
  test-ruby:
    env:
      ENDPOINT: http://localhost:8080
    strategy:
      matrix:
        ruby: [ 2.7, 3.0, 3.1 ]

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
    - name: Build and test with Rake
      run: |
        ruby -v
        bundle install
        bundle exec rake spec:client
  test-jruby:
    env:
      ENDPOINT: http://localhost:3002/api/ws/v1
    strategy:
      fail-fast: false
      matrix:
        ruby: [ jruby-9.3 ]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
    - name: Build and test with Rake
      run: |
        ruby -v
        bundle install
        bundle exec rake spec:client
